# Generated by Django 4.2.6 on 2023-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv_av', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='Sigla do Estado'),
        ),
    ]
